server:
  port: 8080
spring:
  application:
    name: "products"
  profiles:
    active: ""
  datasource:
    url: jdbc:mysql://localhost:3306/product
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    name : "products"
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    lease-renewal-interval-in-seconds: 30
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "products"
    description: "DemoApp products Application"
    version: "1.0.0"
